# permissions for end users to view btpmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: btpmanager-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpmanagers/status
  verbs:
  - get
