# permissions for end users to edit btpmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: btpmanager-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpmanagers/status
  verbs:
  - get
